pipeline {
  agent {
    kubernetes {
      yamlFile 'terraform/jenkins-agent.yaml'
    }
  }

  environment {
    DOCKER_IMAGE = "atatara/flask-app:${env.BUILD_NUMBER}"
    APP_DIR = "terraform/flask-app"
  }

  stages {
    stage('Checkout') {
      steps {
        container('jnlp') {
          checkout scm
        }
      }
    }

    stage('Install dependencies & run tests') {
      steps {
        container('python') {
          sh '''
            cd terraform/flask-app
            pip install -r requirements.txt
            pip install pytest coverage
            coverage run -m pytest tests/ --junitxml=report.xml
            coverage xml -o coverage.xml
          '''
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        container('sonar') {
          withSonarQubeEnv('SonarQube') {
            dir("${APP_DIR}") {
              sh 'sonar-scanner'
            }
          }
        }
      }
    }

    stage('Docker Build') {
      steps {
        container('docker') {
          dir("${APP_DIR}") {
            sh "docker build -t ${DOCKER_IMAGE} ."
          }
        }
      }
    }

    stage('Push Docker image') {
      steps {
        container('docker') {
          withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh '''
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker push ${DOCKER_IMAGE}
            '''
          }
        }
      }
    }

    stage('Helm Deploy') {
      steps {
        container('helm') {
          sh '''
            helm upgrade --install flask-app ./flask-app-chart \
              --namespace devops-tools \
              --create-namespace \
              --set image.repository=atatara/flask-app \
              --set image.tag=${BUILD_NUMBER}
          '''
        }
      }
    }
  }

  post {
    success {
      echo "Pipeline completed successfully."
    }
    failure {
      echo "Pipeline failed."
    }
  }
}
