apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
    - name: python
      image: python:3.11
      command:
        - cat
      tty: true
    - name: docker
      image: docker:24.0.7-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    - name: sonar
      image: sonarsource/sonar-scanner-cli:latest
      command:
        - cat
      tty: true
    - name: helm
      image: alpine/helm:3.14.0
      command:
        - cat
      tty: true
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
